### ISSUE TITLE
[3 주차] 5.1 트랜잭션 ~ 5.2 MySQL 엔진의 잠금

### ISSUE THREAD

**Issue by gutenLEE** [WanOnPreStudy/study-real-my-sql#12]
주차 : 3
분량 : 5.1 트랜잭션 ~ 5.2 MySQL 엔진의 잠금
마감일 : 2022년 12월 26일 오후 8시
발표자 : @gutenLEE

**Comment by sm9171** [comment]
안녕하세요 질문이 생겨서 여쭤보고자 합니다.

`5.2.2 테이블 락` 섹션 부분에서 InnoDB 테이블의 같은 경우에는 레코드 기반의 잠금을 제공하기 때문에  테이블락이 데이터 변경(DML) 쿼리에서는 무시되고 스키마을 변경하는 쿼리(DDL)의 경우에만 영향을 미친다는데

InnoDB테이블의 레코드 기반의 잠금이 테이블락 결과값에 미치는 이유에 대해 궁금하네요.
